"""refactor_database_schema

Revision ID: fb23dc6574fb
Revises: 
Create Date: 2026-06-28 01:01:31.587036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb23dc6574fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE rarity_enum ADD VALUE IF NOT EXISTS 'Epic'")
        op.execute("ALTER TYPE rarity_enum ADD VALUE IF NOT EXISTS 'Unique'")

    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sync_mode', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('items_imported', sa.Integer(), nullable=False),
    sa.Column('items_updated', sa.Integer(), nullable=False),
    sa.Column('items_skipped', sa.Integer(), nullable=False),
    sa.Column('duplicates_detected', sa.Integer(), nullable=False),
    sa.Column('validation_errors', sa.Integer(), nullable=False),
    sa.Column('prices_updated', sa.Integer(), nullable=False),
    sa.Column('images_downloaded', sa.Integer(), nullable=False),
    sa.Column('images_reused', sa.Integer(), nullable=False),
    sa.Column('failures_log', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_summary',
    sa.Column('master_item_id', sa.Integer(), nullable=False),
    sa.Column('market_hash_name', sa.String(length=512), nullable=False),
    sa.Column('market_url', sa.Text(), nullable=True),
    sa.Column('latest_price_idr', sa.Float(), nullable=True),
    sa.Column('latest_price_usd', sa.Float(), nullable=True),
    sa.Column('median_price_idr', sa.Float(), nullable=True),
    sa.Column('median_price_usd', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=16), nullable=True),
    sa.Column('market_status', sa.String(length=32), nullable=False),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['master_item_id'], ['master_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('master_item_id')
    )
    op.create_index(op.f('ix_market_summary_market_hash_name'), 'market_summary', ['market_hash_name'], unique=True)
    op.create_index(op.f('ix_market_summary_master_item_id'), 'market_summary', ['master_item_id'], unique=False)
    op.add_column('master_items', sa.Column('internal_item_id', sa.Integer(), nullable=True))
    op.add_column('master_items', sa.Column('normalized_name', sa.String(length=512), nullable=True))
    op.add_column('master_items', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('master_items', sa.Column('class_type', sa.String(length=64), nullable=True))
    op.add_column('master_items', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('master_items', sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('master_items', sa.Column('category', sa.String(length=128), nullable=True))
    op.add_column('master_items', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('master_items', sa.Column('image_path', sa.String(length=512), nullable=True))
    op.add_column('master_items', sa.Column('image_hash', sa.String(length=64), nullable=True))
    op.add_column('master_items', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('master_items', 'market_hash_name',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.create_index('idx_master_items_filters', 'master_items', ['rarity', 'item_type', 'gear_type', 'class_type', 'level'], unique=False)
    op.create_index(op.f('ix_master_items_internal_item_id'), 'master_items', ['internal_item_id'], unique=True)
    op.create_index(op.f('ix_master_items_normalized_name'), 'master_items', ['normalized_name'], unique=False)
    op.drop_column('master_items', 'icon_url')
    op.create_index('idx_price_alerts_active', 'price_alerts', ['is_active', 'expires_at'], unique=False)
    op.create_index('idx_price_history_item_date', 'price_history', ['master_item_id', 'fetched_at'], unique=False)
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('role', sa.String(length=32), server_default='user', nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('idx_users_google_auth', 'users', ['google_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_google_auth', table_name='users')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'role')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'google_id')
    op.drop_index('idx_price_history_item_date', table_name='price_history')
    op.drop_index('idx_price_alerts_active', table_name='price_alerts')
    op.add_column('master_items', sa.Column('icon_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_master_items_normalized_name'), table_name='master_items')
    op.drop_index(op.f('ix_master_items_internal_item_id'), table_name='master_items')
    op.drop_index('idx_master_items_filters', table_name='master_items')
    op.alter_column('master_items', 'market_hash_name',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.drop_column('master_items', 'updated_at')
    op.drop_column('master_items', 'image_hash')
    op.drop_column('master_items', 'image_path')
    op.drop_column('master_items', 'metadata')
    op.drop_column('master_items', 'category')
    op.drop_column('master_items', 'stats')
    op.drop_column('master_items', 'level')
    op.drop_column('master_items', 'class_type')
    op.drop_column('master_items', 'description')
    op.drop_column('master_items', 'normalized_name')
    op.drop_column('master_items', 'internal_item_id')
    op.drop_index(op.f('ix_market_summary_master_item_id'), table_name='market_summary')
    op.drop_index(op.f('ix_market_summary_market_hash_name'), table_name='market_summary')
    op.drop_table('market_summary')
    op.drop_table('sync_logs')
    # ### end Alembic commands ###
